input_data_path: 'data/heart.csv'
output_model_path: 'models/model_rf.pkl'
metrics_path: 'models/metrics_rf.json'
splitting_params:
  random_state: 42
  val_size: 0.3
  shuffle: True
clf_params:
  model_type: 'RandomForestClassifier'
  random_state: 42
  n_estimators: 20
  max_depth: 4
feature_params:
  num_features:
    - 'age'
    - 'cp'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  cat_features:
    - 'thal'
    - 'restecg'
    - 'ca'
    - 'slope'
  bin_features:
    - 'sex'
    - 'fbs'
    - 'exang'
target: 'target'